# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_verify', models.BooleanField(default=False)),
                ('code', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=8)),
                ('type', models.CharField(choices=[('register', 'register'), ('forget', 'forget')], default='register', max_length=20, verbose_name='Code Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_passcodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Passcode',
                'verbose_name_plural': 'User Passcodes',
            },
        ),
    ]
