# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 08:46
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Currency Name')),
                ('code', models.CharField(max_length=20, verbose_name='Short Code')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPerDayRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('target_currency', models.CharField(default='USD', max_length=10)),
                ('change', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_per_day', to='currency.Currency')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Currency Per Day Rate',
                'verbose_name_plural': 'Currency Per Day Rates',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPerHourRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('target_currency', models.CharField(default='USD', max_length=10)),
                ('change', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('timestamp', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_per_hour', to='currency.Currency')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Currency Per Hour Rate',
                'verbose_name_plural': 'Currency Per Hour Rates',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('SOLD', 'SOLD'), ('BOUGHT', 'BOUGHT')], max_length=255, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('message', models.TextField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_transaction', to='currency.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_currencies', to='currency.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_currencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Currency',
                'verbose_name_plural': 'User Currencies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('name', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercurrency',
            unique_together=set([('currency', 'user')]),
        ),
    ]
